line-length = 120
target-version = "py313"

[format]
docstring-code-format = true
docstring-code-line-length = 80
quote-style = "double"
line-ending = "lf"
skip-magic-trailing-comma = true

[lint]
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
    "D", # Docstrings
    "COM812",  # Missing trailing comma (interferes with the formatter)
    "FBT003",
    "EM101",
    "TRY003"
]

[lint.per-file-ignores]
"**/__init__.py" = [
    "F403",
    "F401",
]



[lint.isort]
required-imports = ["from __future__ import annotations"]
force-single-line = true

[lint.pydocstyle]
convention = "numpy"

[lint.pylint]
max-args = 20

[lint.mccabe]
max-complexity = 20